[package]
name = "wcpopup"
version = "0.1.18"
edition = "2021"
description = "Context menu for Windows"
documentation = "https://docs.rs/wcpopup/0.1.18/wcpopup/"
readme = "README.md"
categories = ["gui"]
license = "MIT"
repository = "https://github.com/mrdkprj/wcpopup"
exclude = [
    "/assets"
]

[features]
default = []
"accelerator" = []

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = [
  "x86_64-pc-windows-msvc"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.19.0"
windows-version = "0.1.1"

[dependencies.windows]
version = "0.57"
features = [
    "Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls",
    "Win32_UI_Shell",
    "Win32_System",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Globalization",
    "Win32_System_Threading",
    "Win32_Graphics_Dwm",
    "UI_ViewManagement",
]